### ISSUE TITLE
Cavatica API endpoint is hardcoded in main.py

### ISSUE THREAD

**Issue by groverj3** [include-dcc/sbpack-action#1]
Hi there,

Thanks for making this! I was intending on making one, myself, but found yours. No need to reinvent the wheel :). I tested this action, and found that the API endpoint for Cavatica is hardcoded. I understand that INCLUDE uses that platform. However, there isn't anything stopping this from being broadly useful if the API endpoint can be passed from the .yml like app_name, workflow_path, auth_token, etc.

**Comment by thomasyu888** [comment]
Thanks for noting that. I shall make that change next week after I get back in the office.

**Comment by thomasyu888** [comment]
@groverj3. This is supported in version v0.0.2

**Comment by groverj3** [comment]
Thanks, @thomasyu888. Tested this yesterday and it's working nicely. I've put together an example of using it to push to the CGC [here](https://github.com/rabix/sb-ci).
